// Command agent runs on a remote host and pushes metrics to the aperture hub
// over a persistent WebSocket connection. The agent connects OUT to the hub
// (works through NAT/firewalls without port forwarding) and authenticates
// with a pre-shared token generated by the hub UI.
//
// The agent reuses the same internal/collector and internal/dockerctl packages
// as the hub's local mode — it is a thin WebSocket transport wrapper around
// the same code.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/aperture/aperture/internal/agentproto"
	"github.com/aperture/aperture/internal/collector"
	"github.com/aperture/aperture/internal/compose"
	"github.com/aperture/aperture/internal/dockerctl"
	"github.com/aperture/aperture/internal/types"
	"github.com/coder/websocket"
	"github.com/coder/websocket/wsjson"
)

const agentVersion = "0.4.0-alpha.2"

// ── wire frame types (must match hub/agentws.go) ────────────────────────────

type helloFrame struct {
	Type       string         `json:"type"`
	Host       types.HostInfo `json:"host"`
	Version    string         `json:"version"`
	HasDocker  bool           `json:"has_docker"`
	HasCompose bool           `json:"has_compose"`
}

type composeReqFrame struct {
	Type       string   `json:"type"`
	ReqID      string   `json:"req_id"`
	Action     string   `json:"action"`
	Project    string   `json:"project,omitempty"`
	WorkingDir string   `json:"working_dir,omitempty"`
	SubAction  string   `json:"sub_action,omitempty"`
	Service    string   `json:"service,omitempty"`
	ExtraArgs  []string `json:"extra_args,omitempty"`
	Content    string   `json:"content,omitempty"`
	Tail       int      `json:"tail,omitempty"`
}

type composeRespFrame struct {
	Type  string          `json:"type"`
	ReqID string          `json:"req_id"`
	OK    bool            `json:"ok"`
	Data  json.RawMessage `json:"data,omitempty"`
	Error string          `json:"error,omitempty"`
}

type ackFrame struct {
	Type   string `json:"type"`
	HostID string `json:"host_id"`
}

type metricFrame struct {
	Type string             `json:"type"`
	Data types.MetricSample `json:"data"`
}

type heartbeatFrame struct {
	Type string `json:"type"` // "heartbeat"
}

type dockerReqFrame struct {
	Type   string          `json:"type"`
	ReqID  string          `json:"req_id"`
	Action string          `json:"action"`
	CID    string          `json:"cid,omitempty"`
	Params json.RawMessage `json:"params,omitempty"`
}

type dockerRespFrame struct {
	Type  string          `json:"type"`
	ReqID string          `json:"req_id"`
	OK    bool            `json:"ok"`
	Data  json.RawMessage `json:"data,omitempty"`
	Error string          `json:"error,omitempty"`
}

type terminalReqFrame struct {
	Type   string `json:"type"` // "terminal_req"
	ReqID  string `json:"req_id"`
	Action string `json:"action"` // "start", "resize", "close"
	CID    string `json:"cid,omitempty"`
	Cmd    string `json:"cmd,omitempty"`
	Cols   uint   `json:"cols,omitempty"`
	Rows   uint   `json:"rows,omitempty"`
}

type terminalRespFrame struct {
	Type  string `json:"type"` // "terminal_resp"
	ReqID string `json:"req_id"`
	OK    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
}

type terminalDataFrame struct {
	Type  string `json:"type"` // "terminal_data"
	ReqID string `json:"req_id"`
	Data  []byte `json:"data"` // base64 decoded automatically
}

type agentFrame struct {
	Type string `json:"type"`
}

var (
	activeTerminalsMu sync.Mutex
	activeTerminals   = make(map[string]*terminalSession)
)

type terminalSession struct {
	stdin  io.WriteCloser
	resize func(cols, rows uint) error
	close  func()
}

// ── main ─────────────────────────────────────────────────────────────────────

func main() {
	var (
		hubURL   = flag.String("hub", "", "URL of the hub (e.g. http://192.168.1.10:8080) [required]")
		token    = flag.String("token", "", "Agent token generated by the hub UI [required]")
		name     = flag.String("name", "", "Override hostname (default: system hostname)")
		interval = flag.Duration("interval", 5*time.Second, "Metric sample interval")
		diskPath = flag.String("disk", "/", "Filesystem path to report disk usage for")
		noDocker = flag.Bool("no-docker", false, "Disable docker collection even if socket is available")
	)
	flag.Parse()

	log := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	slog.SetDefault(log)

	if *hubURL == "" || *token == "" {
		fmt.Fprintln(os.Stderr, "error: --hub and --token are required")
		flag.Usage()
		os.Exit(1)
	}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	wsURL := hubToWS(*hubURL)

	// Build collector — HostInfo() is cheap to call repeatedly.
	col := collector.NewLocal(*interval)
	col.DiskPath = *diskPath

	// Resolve host info once; optionally override the name.
	info := col.HostInfo()
	if *name != "" {
		info.Name = *name
	}
	info.Source = "agent"

	// Probe docker once at startup.
	hasDocker := false
	var dc *dockerctl.Client
	if !*noDocker {
		if c, err := dockerctl.New(""); err == nil {
			if err := c.Ping(ctx); err == nil {
				hasDocker = true
				dc = c
				log.Info("docker provider active")
			} else {
				_ = c.Close()
			}
		}
	}

	// Probe docker compose availability.
	var lc *compose.Local
	if hasDocker {
		if c, err := compose.NewLocal(); err == nil {
			lc = c
			log.Info("compose provider active")
		} else {
			log.Warn("compose not available", "err", err)
		}
	}

	// Reconnect loop with exponential backoff.
	backoff := 2 * time.Second
	const maxBackoff = 60 * time.Second

	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		log.Info("connecting to hub", "url", wsURL)
		err := runSession(ctx, log, wsURL, *token, info, col, hasDocker, dc, lc)
		if ctx.Err() != nil {
			return
		}
		if err == nil {
			// Clean close — retry immediately with reset backoff.
			backoff = 2 * time.Second
			continue
		}

		log.Info("disconnected; retrying", "err", err, "in", backoff)
		select {
		case <-time.After(backoff):
		case <-ctx.Done():
			return
		}
		backoff *= 2
		if backoff > maxBackoff {
			backoff = maxBackoff
		}
	}
}

// hubToWS converts an http/https URL to ws/wss and appends the agent path.
func hubToWS(hubURL string) string {
	u := strings.TrimRight(hubURL, "/")
	u = strings.Replace(u, "https://", "wss://", 1)
	u = strings.Replace(u, "http://", "ws://", 1)
	return u + "/api/agents/ws"
}

// runSession establishes one WebSocket session, runs the metric+docker+compose loop,
// and returns when the connection drops or ctx is cancelled.
func runSession(
	ctx context.Context,
	log *slog.Logger,
	wsURL, token string,
	info types.HostInfo,
	col *collector.Local,
	hasDocker bool,
	dc *dockerctl.Client,
	lc *compose.Local,
) error {
	hdr := http.Header{}
	hdr.Set("Authorization", "Bearer "+token)

	conn, _, err := websocket.Dial(ctx, wsURL, &websocket.DialOptions{
		HTTPHeader: hdr,
	})
	if err != nil {
		return fmt.Errorf("dial: %w", err)
	}
	defer conn.CloseNow()

	// Send hello.
	hello := helloFrame{
		Type:       "hello",
		Host:       info,
		Version:    agentVersion,
		HasDocker:  hasDocker,
		HasCompose: lc != nil,
	}
	if err := wsjson.Write(ctx, conn, hello); err != nil {
		return fmt.Errorf("write hello: %w", err)
	}

	// Wait for ack (15s timeout).
	ackCtx, ackCancel := context.WithTimeout(ctx, 15*time.Second)
	var raw json.RawMessage
	if err := wsjson.Read(ackCtx, conn, &raw); err != nil {
		ackCancel()
		return fmt.Errorf("read ack: %w", err)
	}
	ackCancel()

	var af agentFrame
	_ = json.Unmarshal(raw, &af)
	if af.Type != "ack" {
		return fmt.Errorf("expected ack, got %q", af.Type)
	}
	var ack ackFrame
	_ = json.Unmarshal(raw, &ack)
	log.Info("connected", "host_id", ack.HostID)

	// Session-scoped context so goroutines clean up when the read loop exits.
	sessCtx, sessCancel := context.WithCancel(ctx)
	defer sessCancel()

	// Start metric collector goroutine.
	metricCh := make(chan types.MetricSample, 8)
	go func() {
		_ = col.Run(sessCtx, metricCh)
	}()

	// Heartbeat goroutine (every 5s).
	go func() {
		t := time.NewTicker(5 * time.Second)
		defer t.Stop()
		for {
			select {
			case <-sessCtx.Done():
				return
			case <-t.C:
				_ = wsjson.Write(sessCtx, conn, heartbeatFrame{Type: "heartbeat"})
			}
		}
	}()

	// Metric send goroutine.
	go func() {
		for {
			select {
			case <-sessCtx.Done():
				return
			case s, ok := <-metricCh:
				if !ok {
					return
				}
				mf := metricFrame{Type: "metric", Data: s}
				if err := wsjson.Write(sessCtx, conn, mf); err != nil {
					return
				}
			}
		}
	}()

	// Main read loop: receive docker_req frames from the hub.
	for {
		var msg json.RawMessage
		if err := wsjson.Read(ctx, conn, &msg); err != nil {
			return err
		}
		var peek agentFrame
		if err := json.Unmarshal(msg, &peek); err != nil {
			continue
		}
		switch peek.Type {
		case "docker_req":
			if dc == nil {
				continue
			}
			var req dockerReqFrame
			if err := json.Unmarshal(msg, &req); err != nil {
				continue
			}
			go handleDockerReq(ctx, log, conn, dc, req)
		case "compose_req":
			if lc == nil {
				continue
			}
			var req composeReqFrame
			if err := json.Unmarshal(msg, &req); err != nil {
				continue
			}
			go handleComposeReq(ctx, log, conn, lc, req)
		case "terminal_req":
			if dc == nil {
				continue
			}
			var req terminalReqFrame
			if err := json.Unmarshal(msg, &req); err != nil {
				continue
			}
			go handleTerminalReq(ctx, log, conn, dc, req)
		case "terminal_data":
			var req terminalDataFrame
			if err := json.Unmarshal(msg, &req); err != nil {
				continue
			}
			go handleTerminalData(ctx, req)
		case "config":
			// Hub pushed an updated monitoring policy for this host. Apply
			// to the local collector — takes effect on the next tick.
			var cf agentproto.ConfigFrame
			if err := json.Unmarshal(msg, &cf); err != nil {
				log.Warn("decode config frame", "err", err)
				continue
			}
			col.ApplyConfig(types.HostConfig{
				SampleIntervalS: cf.SampleIntervalS,
				EnabledFamilies: cf.EnabledFamilies,
				Filters:         cf.Filters,
				MemCalc:         cf.MemCalc,
			})
			log.Info("applied config from hub",
				"interval_s", cf.SampleIntervalS,
				"families", cf.EnabledFamilies)
		}
	}
}

// handleDockerReq dispatches one docker_req to the local docker daemon and
// sends the result back as a docker_resp.
func handleDockerReq(ctx context.Context, log *slog.Logger, conn *websocket.Conn, dc *dockerctl.Client, req dockerReqFrame) {
	resp := dockerRespFrame{
		Type:  "docker_resp",
		ReqID: req.ReqID,
	}

	data, err := dispatchDocker(ctx, dc, req)
	if err != nil {
		resp.OK = false
		resp.Error = err.Error()
		log.Warn("docker req failed", "action", req.Action, "err", err)
	} else {
		resp.OK = true
		resp.Data = data
	}

	if werr := wsjson.Write(ctx, conn, resp); werr != nil {
		log.Warn("write docker_resp failed", "req_id", req.ReqID, "err", werr)
	}
}

func handleTerminalReq(ctx context.Context, log *slog.Logger, conn *websocket.Conn, dc *dockerctl.Client, req terminalReqFrame) {
	if req.Action == "start" {
		stdin, outCh, resizeFn, closeFn, err := dc.StartTerminal(ctx, req.CID, req.Cmd)
		
		resp := terminalRespFrame{
			Type:  "terminal_resp",
			ReqID: req.ReqID,
			OK:    err == nil,
		}
		if err != nil {
			resp.Error = err.Error()
		}
		if werr := wsjson.Write(ctx, conn, resp); werr != nil {
			log.Warn("write terminal_resp failed", "err", werr)
		}

		if err == nil {
			activeTerminalsMu.Lock()
			activeTerminals[req.ReqID] = &terminalSession{
				stdin:  stdin,
				resize: resizeFn,
				close:  closeFn,
			}
			activeTerminalsMu.Unlock()

			// Read from outCh and send to hub
			go func() {
				for chunk := range outCh {
					dataFrame := terminalDataFrame{
						Type:  "terminal_data",
						ReqID: req.ReqID,
						Data:  chunk,
					}
					wsjson.Write(ctx, conn, dataFrame)
				}
				// Cleanup on close
				activeTerminalsMu.Lock()
				delete(activeTerminals, req.ReqID)
				activeTerminalsMu.Unlock()
			}()
		}
	} else if req.Action == "resize" {
		activeTerminalsMu.Lock()
		sess, ok := activeTerminals[req.ReqID]
		activeTerminalsMu.Unlock()
		if ok && sess.resize != nil {
			sess.resize(req.Cols, req.Rows)
		}
	} else if req.Action == "close" {
		activeTerminalsMu.Lock()
		sess, ok := activeTerminals[req.ReqID]
		if ok {
			delete(activeTerminals, req.ReqID)
		}
		activeTerminalsMu.Unlock()
		if ok && sess.close != nil {
			sess.close()
		}
	}
}

func handleTerminalData(ctx context.Context, req terminalDataFrame) {
	activeTerminalsMu.Lock()
	sess, ok := activeTerminals[req.ReqID]
	activeTerminalsMu.Unlock()
	if ok && sess.stdin != nil {
		sess.stdin.Write(req.Data)
	}
}

// dispatchDocker routes a docker_req action to the appropriate dockerctl method.
func dispatchDocker(ctx context.Context, dc *dockerctl.Client, req dockerReqFrame) (json.RawMessage, error) {
	switch req.Action {
	case "list":
		var p struct {
			All bool `json:"all"`
		}
		_ = json.Unmarshal(req.Params, &p)
		containers, err := dc.List(ctx, p.All)
		if err != nil {
			return nil, err
		}
		return json.Marshal(containers)

	case "create":
		var spec types.CreateSpec
		if err := json.Unmarshal(req.Params, &spec); err != nil {
			return nil, fmt.Errorf("unmarshal create spec: %w", err)
		}
		id, err := dc.Create(ctx, spec)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"id": id})

	case "start":
		if err := dc.Start(ctx, req.CID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "stop":
		var p struct {
			TimeoutSec *int `json:"timeout_sec"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.Stop(ctx, req.CID, p.TimeoutSec); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "restart":
		var p struct {
			TimeoutSec *int `json:"timeout_sec"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.Restart(ctx, req.CID, p.TimeoutSec); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "pause":
		if err := dc.Pause(ctx, req.CID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "unpause":
		if err := dc.Unpause(ctx, req.CID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "kill":
		var p struct {
			Signal string `json:"signal"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if p.Signal == "" {
			p.Signal = "SIGTERM"
		}
		if err := dc.Kill(ctx, req.CID, p.Signal); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "remove":
		var p struct {
			Force         bool `json:"force"`
			RemoveVolumes bool `json:"remove_volumes"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.Remove(ctx, req.CID, p.Force, p.RemoveVolumes); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "logs":
		var p struct {
			Tail       int   `json:"tail"`
			Since      int64 `json:"since"`
			Timestamps bool  `json:"timestamps"`
		}
		_ = json.Unmarshal(req.Params, &p)
		var since time.Time
		if p.Since > 0 {
			since = time.Unix(p.Since, 0)
		}
		logs, err := dc.Logs(ctx, req.CID, p.Tail, since, p.Timestamps)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"logs": logs})

	case "inspect":
		info, err := dc.Inspect(ctx, req.CID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(info)

	case "update_resources":
		var update types.ResourceUpdate
		if err := json.Unmarshal(req.Params, &update); err != nil {
			return nil, fmt.Errorf("unmarshal update_resources: %w", err)
		}
		if err := dc.UpdateResources(ctx, req.CID, update); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "list_networks":
		nets, err := dc.ListNetworks(ctx)
		if err != nil {
			return nil, err
		}
		if nets == nil {
			nets = []types.DockerNetwork{}
		}
		return json.Marshal(nets)

	case "inspect_network":
		n, err := dc.InspectNetwork(ctx, req.CID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(n)

	case "create_network":
		var spec types.NetworkCreateSpec
		if err := json.Unmarshal(req.Params, &spec); err != nil {
			return nil, fmt.Errorf("unmarshal create network spec: %w", err)
		}
		id, err := dc.CreateNetwork(ctx, spec)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"id": id})

	case "remove_network":
		if err := dc.RemoveNetwork(ctx, req.CID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "connect_network":
		var p struct {
			ContainerID string `json:"container_id"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.ConnectContainer(ctx, req.CID, p.ContainerID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "disconnect_network":
		var p struct {
			ContainerID string `json:"container_id"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.DisconnectContainer(ctx, req.CID, p.ContainerID); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "list_volumes":
		vols, err := dc.ListVolumes(ctx)
		if err != nil {
			return nil, err
		}
		if vols == nil {
			vols = []types.DockerVolume{}
		}
		return json.Marshal(vols)

	case "inspect_volume":
		v, err := dc.InspectVolume(ctx, req.CID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(v)

	case "create_volume":
		var spec types.VolumeCreateSpec
		if err := json.Unmarshal(req.Params, &spec); err != nil {
			return nil, fmt.Errorf("unmarshal create volume spec: %w", err)
		}
		name, err := dc.CreateVolume(ctx, spec)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"name": name})

	case "remove_volume":
		var p struct {
			Force bool `json:"force"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.RemoveVolume(ctx, req.CID, p.Force); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "list_images":
		imgs, err := dc.ListImages(ctx)
		if err != nil {
			return nil, err
		}
		if imgs == nil {
			imgs = []types.DockerImage{}
		}
		return json.Marshal(imgs)

	case "inspect_image":
		i, err := dc.InspectImage(ctx, req.CID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(i)

	case "remove_image":
		var p struct {
			Force bool `json:"force"`
		}
		_ = json.Unmarshal(req.Params, &p)
		if err := dc.RemoveImage(ctx, req.CID, p.Force); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "pull_image":
		var spec types.ImagePullSpec
		if err := json.Unmarshal(req.Params, &spec); err != nil {
			return nil, fmt.Errorf("unmarshal pull spec: %w", err)
		}
		if err := dc.PullImage(ctx, spec.Image); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	case "check_image_update":
		status, err := dc.CheckImageUpdate(ctx, req.CID)
		if err != nil {
			return nil, err
		}
		return json.Marshal(status)

	default:
		return nil, fmt.Errorf("unknown docker action: %s", req.Action)
	}
}

// handleComposeReq dispatches one compose_req to the local compose runtime.
func handleComposeReq(ctx context.Context, log *slog.Logger, conn *websocket.Conn, lc *compose.Local, req composeReqFrame) {
	resp := composeRespFrame{
		Type:  "compose_resp",
		ReqID: req.ReqID,
	}
	data, err := dispatchCompose(ctx, lc, req)
	if err != nil {
		resp.OK = false
		resp.Error = err.Error()
		log.Warn("compose req failed", "action", req.Action, "err", err)
	} else {
		resp.OK = true
		resp.Data = data
	}
	if werr := wsjson.Write(ctx, conn, resp); werr != nil {
		log.Warn("write compose_resp failed", "req_id", req.ReqID, "err", werr)
	}
}

// dispatchCompose routes a compose_req to the appropriate compose.Local method.
func dispatchCompose(ctx context.Context, lc *compose.Local, req composeReqFrame) (json.RawMessage, error) {
	switch req.Action {
	case "discover":
		stacks, err := lc.DiscoverStacks(ctx)
		if err != nil {
			return nil, err
		}
		if stacks == nil {
			stacks = []types.ComposeStack{}
		}
		return json.Marshal(stacks)

	case "get_stack":
		stack, err := lc.GetStack(ctx, req.Project)
		if err != nil {
			return nil, err
		}
		return json.Marshal(stack)

	case "exec":
		out, err := lc.StackAction(ctx, req.Project, req.WorkingDir, req.SubAction, req.Service, req.ExtraArgs...)
		if err != nil {
			// Include output in error so the caller can show it.
			return nil, err
		}
		return json.Marshal(map[string]string{"output": out})

	case "logs":
		out, err := lc.Logs(ctx, req.Project, req.WorkingDir, req.Service, req.Tail)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"output": out})

	case "read_file":
		content, err := lc.ReadFile(ctx, req.WorkingDir)
		if err != nil {
			return nil, err
		}
		return json.Marshal(map[string]string{"content": content})

	case "write_file":
		if err := lc.WriteFile(ctx, req.WorkingDir, req.Content); err != nil {
			return nil, err
		}
		return json.Marshal(map[string]bool{"ok": true})

	default:
		return nil, fmt.Errorf("unknown compose action: %s", req.Action)
	}
}
